POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "Bolo no pote",
  "description": "o melhor bolo no pote",
  "price": "20.00",
  "image": "imagem",
  "category": "acai",
  "authorId": 15
}